### ISSUE TITLE
Reproduce the result

### ISSUE THREAD

**Issue by tamltlkdn** [nutellamok/advrush#2]
Hi !
Thanks for sharing the code. 
I am unable to reproduce the result from the paper. Using the command provided, I trained ADVRUSH (adv training) and got 85.69% clean ACC and 45.45% PGD20 while the paper reported 87.3% clean ACC and 53.07% PGD20. What am I missing here?

**Comment by Jialiang14** [comment]
me too!

**Comment by nutellamok** [comment]
I believe the architecture achieves the best performance around ~100-105 epoch of training. I recommend using that checkpoint instead of the final model after full 200 epochs of training.
